// let i;
// function words (){
//     for(i=1;i<=10;i++){
//         console.log(i)
//     }
//     return i;
// }
// words();

// let j;
// function even(){
//     for(j=1;j<=20;j++){
//         if(j%2==0){
//             console.log(j);
//         }
//     }
//     return j;
// }
// even ();

// let k;
// function odd(){
//     for(k=1;k<=20;k++){
//         if(k%2==1){
//             console.log(k);
//         }
//     }
//     return k;
// }
// odd();


// let l;
// let m;
// function square(){
//     for(l=1;l<=5;l++){
//         m=l*l;
//         console.log(m)
//     }
//     return m;
// }
// square();


// let sum=0;
// let n;
// function som(){
//     for(n=1;n<=100;n++){
//         sum=sum+n;
        
//     }
//     console.log(sum);
//     return sum;
// }
// som();


// let arr=[10,20,30,40,50];
// let o;
// function array(){
//     for(o=0;o<5;o++){
//         console.log(arr[o]);
//     }
//     return arr[o];
// }
// array();



// let arre=[10,20,30,40,50];
// let p;
// function arrays(){
//     for(p=0;p<5;p++){
//         if(arre[p]>25){
//             console.log(arre[p])
//         }
//     }
//     return arre[p];
// }
// arrays();



// let q;
// let sums=0;
// let a=[10,20,30,40,50];
// function arrSums(){
//     for(q=0;q<5;q++){
//         sums=sums+a[q];
//     }
//     console.log(sums);
//     return sums;
// }
// arrSums();


// let r;
// let fact=1;
// function factorial(){
//     for(r=1;r<=5;r++){
//         fact=fact*r
//     }
//     console.log(fact)
//     return fact;
// }
// factorial();


// let s;
// function reverse(){
//     for(s=10;s>=1;s--){
//         console.log(s)
//     }
//     return s;
// }
// reverse();



// let t;
// let Table;
// function multiply7(){
//     for(t=1;t<=10;t++){
//         Table=t*7
//         console.log(Table)
//     }
//     return Table;
// }
// multiply7()

 

// let one_to_ten =(n)=>{
//     let i=1;
//     while(i<=n){
//         console.log(i);
//         i++;
//     }
// }
// one_to_ten(10);


// let fun = (n)=>{
//     let i=1; 
//    let sum= 0;
//    while(i<=n){
//        sum += i;
//         i++
//     }
//     console.log(sum);
// }
// fun(50);


// let fun = (n)=>{
    
//     let i=0;
//     while(i<=n){
//         if(i%2!=0){
//             console.log(i);
//         }
//         i++;
//     }
    

// }
// fun(30);


// let fun = (n)=>{
    
//     let i=n;
//     while(i>=0){
//         console.log(i);
//         i--;
//     }
    

// }
// fun(10);



// let helloworld =(n) =>{
//     let i =1;
//     do {
        
//         console.log("Hello World");
//         i++;
//     } while (i<=n);

// }
// helloworld(5);




// let fun =(n)=>{
//     n.forEach(element => {
//         console.log(element);
        
//     });
// }



// let arr = ['apple','banana','cherry'];
// fun(arr);



// let max =(n)=>{
//     let i=1;
//     let k=n.length
//     let maxi = n[0];
//     do{
//         if(maxi<n[i]){
//             maxi=n[i];
//         }

//         i++;
//     }
//     while(i<k)
//         console.log(maxi);
// }
// max([3,1,5,9,2]);




// let count =(n)=>{
//     let count=0;
//     let k= n.length;
//     for(let i=0;i<k;i++){
//         if(n[i]==5){
//             count++;
//         }
//     }
//     console.log(count);

// }
// count([1,5,3,5,4,5]);







// let reverser =(string)=>{
//     let n= string.length;
//     let newstring="";
//     for(let i=0;i<n;i++){
//         newstring += string[n-i-1];

//     }
//     console.log(newstring);
// }
// reverser("hellow");

// let name ='priyanshu';
// let ans = 1;
// let i = name.length - 1;
// while(i >= 0){
//     ans = ans + name[i]; 
//     console.log(ans);
//     i--;
// }

